"""Initial schema complete

Revision ID: 7b0c4cf76c30
Revises: 
Create Date: 2026-08-22 17:22:42.428948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0c4cf76c30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aportantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=False),
    sa.Column('numero_documento', sa.String(), nullable=False),
    sa.Column('razon_social', sa.String(), nullable=False),
    sa.Column('exonerado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_documento', 'numero_documento', name='uix_aportante_doc')
    )
    op.create_index(op.f('ix_aportantes_id'), 'aportantes', ['id'], unique=False)
    op.create_table('plantillas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('modo', sa.String(), nullable=False),
    sa.Column('separador', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantillas_id'), 'plantillas', ['id'], unique=False)
    op.create_table('trabajadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=False),
    sa.Column('numero_documento', sa.String(), nullable=False),
    sa.Column('registro', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('clase_gasto', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registro'),
    sa.UniqueConstraint('tipo_documento', 'numero_documento', name='uix_trabajador_doc')
    )
    op.create_index(op.f('ix_trabajadores_id'), 'trabajadores', ['id'], unique=False)
    op.create_table('versiones_formula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('creado_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versiones_formula_id'), 'versiones_formula', ['id'], unique=False)
    op.create_table('cargas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aportante_id', sa.Integer(), nullable=False),
    sa.Column('operador', sa.String(), nullable=False),
    sa.Column('numero_planilla', sa.String(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('ruta_pdf', sa.String(), nullable=True),
    sa.Column('hash_archivo', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('version_formula_id', sa.Integer(), nullable=True),
    sa.Column('creado_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['aportante_id'], ['aportantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aportante_id', 'periodo', name='uix_carga_periodo')
    )
    op.create_index(op.f('ix_cargas_id'), 'cargas', ['id'], unique=False)
    op.create_table('formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('etiqueta', sa.String(), nullable=False),
    sa.Column('expresion', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['versiones_formula.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'codigo', name='uix_formula_version_codigo'),
    sa.UniqueConstraint('version_id', 'orden', name='uix_formula_version_orden')
    )
    op.create_index(op.f('ix_formulas_id'), 'formulas', ['id'], unique=False)
    op.create_table('mapeo_plantilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('codigo_calculo', sa.String(), nullable=True),
    sa.Column('columna_destino', sa.String(), nullable=True),
    sa.Column('formato', sa.String(), nullable=True),
    sa.Column('longitud', sa.Integer(), nullable=True),
    sa.Column('relleno', sa.String(), nullable=True),
    sa.Column('alineacion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapeo_plantilla_id'), 'mapeo_plantilla', ['id'], unique=False)
    op.create_table('vinculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('aportante_id', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_retiro', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['aportante_id'], ['aportantes.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vinculos_id'), 'vinculos', ['id'], unique=False)
    op.create_table('exportaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carga_id', sa.Integer(), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=False),
    sa.Column('ruta_archivo', sa.String(), nullable=False),
    sa.Column('hash_archivo', sa.String(), nullable=False),
    sa.Column('generado_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exportaciones_id'), 'exportaciones', ['id'], unique=False)
    op.create_table('lineas_nomina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carga_id', sa.Integer(), nullable=False),
    sa.Column('vinculo_id', sa.Integer(), nullable=False),
    sa.Column('dias_afp', sa.Integer(), nullable=False),
    sa.Column('dias_eps', sa.Integer(), nullable=False),
    sa.Column('dias_arp', sa.Integer(), nullable=False),
    sa.Column('dias_ccf', sa.Integer(), nullable=False),
    sa.Column('ibc_pension', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ibc_salud', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ibc_riesgos', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ibc_ccf', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tarifa_riesgos', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('salario_basico', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('nov_ing', sa.Boolean(), nullable=False),
    sa.Column('nov_ret', sa.Boolean(), nullable=False),
    sa.Column('nov_crudas', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ),
    sa.ForeignKeyConstraint(['vinculo_id'], ['vinculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carga_id', 'vinculo_id', name='uix_linea_carga_vinculo')
    )
    op.create_index(op.f('ix_lineas_nomina_id'), 'lineas_nomina', ['id'], unique=False)
    op.create_table('valores_calculados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_editado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('editado_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['linea_id'], ['lineas_nomina.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linea_id', 'codigo', name='uix_valor_linea_codigo')
    )
    op.create_index(op.f('ix_valores_calculados_id'), 'valores_calculados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valores_calculados_id'), table_name='valores_calculados')
    op.drop_table('valores_calculados')
    op.drop_index(op.f('ix_lineas_nomina_id'), table_name='lineas_nomina')
    op.drop_table('lineas_nomina')
    op.drop_index(op.f('ix_exportaciones_id'), table_name='exportaciones')
    op.drop_table('exportaciones')
    op.drop_index(op.f('ix_vinculos_id'), table_name='vinculos')
    op.drop_table('vinculos')
    op.drop_index(op.f('ix_mapeo_plantilla_id'), table_name='mapeo_plantilla')
    op.drop_table('mapeo_plantilla')
    op.drop_index(op.f('ix_formulas_id'), table_name='formulas')
    op.drop_table('formulas')
    op.drop_index(op.f('ix_cargas_id'), table_name='cargas')
    op.drop_table('cargas')
    op.drop_index(op.f('ix_versiones_formula_id'), table_name='versiones_formula')
    op.drop_table('versiones_formula')
    op.drop_index(op.f('ix_trabajadores_id'), table_name='trabajadores')
    op.drop_table('trabajadores')
    op.drop_index(op.f('ix_plantillas_id'), table_name='plantillas')
    op.drop_table('plantillas')
    op.drop_index(op.f('ix_aportantes_id'), table_name='aportantes')
    op.drop_table('aportantes')
    # ### end Alembic commands ###
