"""add_aportante_nits

Revision ID: 9a85b3a41b8a
Revises: 7b0c4cf76c30
Create Date: 2026-08-22 19:23:04.283683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a85b3a41b8a'
down_revision: Union[str, None] = '7b0c4cf76c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aportantes', sa.Column('nit_arl', sa.String(), nullable=True))
    op.add_column('aportantes', sa.Column('nit_ccf', sa.String(), nullable=True))
    op.add_column('aportantes', sa.Column('nit_afp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aportantes', 'nit_afp')
    op.drop_column('aportantes', 'nit_ccf')
    op.drop_column('aportantes', 'nit_arl')
    # ### end Alembic commands ###
