"""Add consecutivo_inicial to Carga

Revision ID: 9d71db951395
Revises: 9a85b3a41b8a
Create Date: 2026-09-04 12:19:18.253932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d71db951395'
down_revision: Union[str, None] = '9a85b3a41b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargas', sa.Column('consecutivo_inicial', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cargas', 'consecutivo_inicial')
    # ### end Alembic commands ###
